### ISSUE TITLE
Handle redirects

### ISSUE THREAD

**Issue by kevva** [kevva/screenshot-stream#14]
Something like https://github.com/ariya/phantomjs/issues/10389#issuecomment-31947910.

**Comment by maboiteaspam** [comment]
It should wait for newer phantomjs given that last comment
https://github.com/ariya/phantomjs/issues/10389#issuecomment-158962088

wait for 2.1, given that release log
http://phantomjs.org/release-2.0.html

```
Note 1: PhantomJS 2.0 is the first release in the 2.x. It has several regressions compared to the previous 1.9 release.
```

**Comment by sindresorhus** [comment]
We're upgraded to PhantomJS 2.1. So this should now be possible. PR welcome :)

**Comment by kevva** [comment]
Apparently, PhantomJS handles redirects by default now judging from the test.

**Comment by kevva** [comment]
Apparently, PhantomJS handles redirects by default now judging from the test.
