### ISSUE TITLE
Change the `jpeg` format to `jpg`

### ISSUE THREAD

**Issue by sindresorhus** [kevva/screenshot-stream#15]
Before we document this in pageres I think we should change the format to `jpg` instead of `jpeg`.

To match the most used extension. I at least find it more natural to use `jpg`.

@kevva Thoughts?

**Comment by kevva** [comment]
Does it work with `jpg`? Check the supported formats on http://phantomjs.org/api/webpage/method/render-base64.html.

**Comment by sindresorhus** [comment]
Probably not, but we can just rewrite it.

**Comment by sindresorhus** [comment]
https://github.com/kevva/screenshot-stream/commit/f968b7d2609f94ca088544ae672da086f45efc24
