### ISSUE TITLE
in ubuntu environment - error while loading shared libraries: libfontconfig.so.1

### ISSUE THREAD

**Issue by procoder-net** [kevva/screenshot-stream#18]
/node_modules/screenshot-stream/node_modules/phantom-bridge/node_modules/phantomjs/lib/phantom/bin/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory"}

https://github.com/ariya/phantomjs/issues/10904

They need us to install on certain linux environment.

sudo apt-get install libfontconfig

**Comment by kevva** [comment]
https://github.com/Medium/phantomjs

**Comment by procoder-net** [comment]
Thanks dude... i found this... https://github.com/ariya/phantomjs/issues/12948

**Comment by procoder-net** [comment]
hope screenshot-stream will use phantomjs 2?
