### ISSUE TITLE
text cropped while generating thumbnail.

### ISSUE THREAD

**Issue by procoder-net** [kevva/screenshot-stream#19]
Here is the actual page where thumbnail needs to be generated...

<img width="504" alt="screen shot 2015-10-21 at 1 51 12 pm" src="https://cloud.githubusercontent.com/assets/5413258/10649819/ee3d12e0-77fa-11e5-95e3-e4fcb2873e72.png">

here is the screen-shot stream generated image.
<img width="555" alt="screen shot 2015-10-21 at 1 51 25 pm" src="https://cloud.githubusercontent.com/assets/5413258/10649820/efd81e88-77fa-11e5-911a-b00932a5f57d.png">

you can check that "product details" text is cut..etc..All the text has similar problem

**Comment by kevva** [comment]
Could you share the page somehow so I can test?
