### ISSUE TITLE
shoul ensure phantomsj stderr is processed by line

### ISSUE THREAD

**Issue by maboiteaspam** [kevva/screenshot-stream#22]
Hi,

In here 
https://github.com/kevva/screenshot-stream/blob/master/index.js#L63

You should ensure the stream is processed by lines, otherwise all the regex can break.

I faced a behavior where data event received chunks composed of multiple lines at once.
It happened when i started to send quiet some data. 
With small amount of exchanged data, I have not noticed that behavior.

fore reference,
I did that
```
var byline = require('byline');
byline(cp.stderr).on('data', function (data) {
    data = data.trim();
...
```

I rely on
https://github.com/jahewson/node-byline

**Comment by sindresorhus** [comment]
:+1:

**Comment by sindresorhus** [comment]
:+1: PR welcome :)

**Comment by maboiteaspam** [comment]
my pleasure ! will leave you something before EOYear.
