### ISSUE TITLE
Unexpected token '>' and  Unexpected token 'in'

### ISSUE THREAD

**Issue by Dexon95** [kevva/screenshot-stream#45]
Hey, i'm having some trouble figuring out this problem. I'm not sure if this comes from this module or phantomjs.

These warnings are returned from little scripts on my test page
`Unexpected token '>' ` :
```javascript
function x(y, z){
  z(y);
}
x('Hey', cb => {
  console.log(cb);
});
```

`Unexpected token 'in'` :
```javascript
var a = {"one": 1, "two": 2, "three": 3};
for(let i in a){
  console.log(a[i]);
}
```

**Comment by SamVerschueren** [comment]
Phantom does not work with ES6 features. Same like older browsers.
