### ISSUE TITLE
Possible to skip unloadable resource?

### ISSUE THREAD

**Issue by Magicloud** [kevva/screenshot-stream#47]
Some webpages show well in browser, but uncapturable with screenshot-stream. I saw same errors on both that some resources cannot be loaded.
Wondering if there is way to make screenshot-stream as tough as browser.

**Comment by SamVerschueren** [comment]
We're switching to Headless Chrome https://github.com/kevva/screenshot-stream/pull/46.

**Comment by Magicloud** [comment]
Thanks.
