### ISSUE TITLE
Turning the stream into a buffer.

### ISSUE THREAD

**Issue by WaqqasI** [kevva/screenshot-stream#48]
I have this code which should turn the stream into a buffer with 'stream-into-array'. However, when utilising this buffer, it doesn't work. When using fs to turn it into a file it works well. 
` const stream = await screenshot(url, '900x1000', {
        crop: true,
        userAgent: 'Mozilla/5.0 (X11; CrOS x86_64 10718.71.2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.87 Safari/537.36',
        css: 'adblock.css',
        delay: 3,
        scale: 1.5
      });
      let buffer;
      await toArray(stream)
      .then(async function (parts) {
        var buffers = []
        for (var i = 0, l = parts.length; i < l ; ++i) {
          var part = parts[i]
          buffers.push((part instanceof Buffer) ? part : new Buffer(part))
        }
        buffer = await Buffer.concat(buffers)
      })`
For more context, I'll be sending this buffer through to discord through discord.js but it seems it's not suitable for it.

**Comment by sindresorhus** [comment]
You should not turn it into an array, but rather into a buffer. You can use [`getStream.buffer()`](https://github.com/sindresorhus/get-stream) for this.
